package com.example.weatherdivkit

import androidx.test.core.app.ActivityScenario
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.example.weatherdivkit.document.DocumentLoader
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Proves the offline last-resort fallback (app/src/main/assets/document.json) renders when the
 * network is unreachable AND there is no cache (see [zero_skeleton_whenOfflineNoCache] for the
 * cache-clearing variant of this same scenario). The bundled asset is now the ZERO SKELETON
 * (generated by scripts/update-bundled-layout.sh from `GET /zero`, not real weather data) — it
 * still carries the same structural ids (header, main_scroll) as the live backend's `/document`,
 * so this test stays green independent of content. `DocumentLoader.loadFromCache` will return
 * null on a clean test device (no prior successful network fetch wrote a cache file), so phase 1
 * of MainActivity's cold start falls through to this asset exactly as before.
 */
@RunWith(AndroidJUnit4::class)
class WeatherOfflineTest {
    private var scenario: ActivityScenario<MainActivity>? = null

    @Before
    fun setUp() { DocumentLoader.baseUrl = "http://127.0.0.1:1" } // dead address -> forces loadFromAssets()

    @After
    fun tearDown() { scenario?.close(); DocumentLoader.baseUrl = DocumentLoader.DEFAULT_BASE_URL }

    @Test
    fun offline_fallsBackToAssets() {
        scenario = ActivityScenario.launch(MainActivity::class.java)
        waitForDivDisplayed("main_scroll")
        dismissPopupIfPresent()

        assertDivDisplayed("header")
        assertDivDisplayed("main_scroll")
    }
}
